// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Link struct {
	ID            int64                 `json:"id"`
	LinkID        uuid.UUID             `json:"link_id"`
	FromLumeID    uuid.UUID             `json:"from_lume_id"`
	ToLumeID      uuid.UUID             `json:"to_lume_id"`
	LinkType      string                `json:"link_type"`
	TravelDetails pqtype.NullRawMessage `json:"travel_details"`
	Notes         sql.NullString        `json:"notes"`
	SequenceIndex sql.NullInt32         `json:"sequence_index"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
}

type Lume struct {
	ID           int64           `json:"id"`
	LumeID       uuid.UUID       `json:"lume_id"`
	LumoID       uuid.UUID       `json:"lumo_id"`
	Type         string          `json:"type"`
	Name         string          `json:"name"`
	DateStart    sql.NullTime    `json:"date_start"`
	DateEnd      sql.NullTime    `json:"date_end"`
	Latitude     sql.NullFloat64 `json:"latitude"`
	Longitude    sql.NullFloat64 `json:"longitude"`
	Address      sql.NullString  `json:"address"`
	Description  sql.NullString  `json:"description"`
	Images       []string        `json:"images"`
	CategoryTags []string        `json:"category_tags"`
	BookingLink  sql.NullString  `json:"booking_link"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}
