// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Lume struct {
	ID          int64                 `json:"id"`
	LumeID      uuid.UUID             `json:"lume_id"`
	LumoID      uuid.UUID             `json:"lumo_id"`
	Label       string                `json:"label"`
	Type        string                `json:"type"`
	Description sql.NullString        `json:"description"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}
