// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateLume(ctx context.Context, arg CreateLumeParams) (Lume, error)
	DeleteLume(ctx context.Context, id int64) error
	GetLumeByID(ctx context.Context, id int64) (Lume, error)
	GetLumeByLumeID(ctx context.Context, lumeID uuid.UUID) (Lume, error)
	ListLumesByLumoID(ctx context.Context, arg ListLumesByLumoIDParams) ([]Lume, error)
	UpdateLume(ctx context.Context, arg UpdateLumeParams) (Lume, error)
}

var _ Querier = (*Queries)(nil)
